CREATE DATABASE SCHOOL;
CREATE TABLE SCHOOL.STUDENT (
    SNO VARCHAR(3) NOT NULL ,
    SNAME VARCHAR(9) NOT NULL ,
    SSEX CHAR(2) NOT NULL
);
INSERT INTO SCHOOL.STUDENT VALUES ('001', 'KangKang', 'M ');
INSERT INTO SCHOOL.STUDENT VALUES ('002', 'Mike', 'M ');
INSERT INTO SCHOOL.STUDENT VALUES ('003', 'Jane', 'F ');